spring:
  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"
    cache: false
    enabled: true
  application:
    name: "Book Collection"
  security:
    user:
        name: "allan"
        password: "secret"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bookscollection;DB_CLOSE_DELAY=-1
    username: allan
    password: secret


server:
  servlet:
    context-path: /
